//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.1434
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ICBOBO")]
public interface ICBOBO
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBOBO/Delete", ReplyAction = "http://tempuri.org/ICBOBO/DeleteResponse")]
    bool Delete(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBOBO/GetCBO", ReplyAction = "http://tempuri.org/ICBOBO/GetCBOResponse")]
    MechTech.Entities.CBODTO GetCBO(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBOBO/GetCBOCodigo", ReplyAction = "http://tempuri.org/ICBOBO/GetCBOCodigoResponse")]
    MechTech.Entities.CBODTO GetCBOCodigo(string codigo);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBOBO/GetGridCBO", ReplyAction = "http://tempuri.org/ICBOBO/GetGridCBOResponse")]
    System.Collections.Generic.List<MechTech.Entities.CBODTO> GetGridCBO(string Campo, string ValorPesquisa);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBOBO/Insert", ReplyAction = "http://tempuri.org/ICBOBO/InsertResponse")]
    int Insert(MechTech.Entities.CBODTO CBO);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBOBO/Update", ReplyAction = "http://tempuri.org/ICBOBO/UpdateResponse")]
    bool Update(MechTech.Entities.CBODTO CBO);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ICBOBOChannel : ICBOBO, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class CBOBOClient : System.ServiceModel.ClientBase<ICBOBO>, ICBOBO
{

    public CBOBOClient()
    {
    }

    public CBOBOClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public CBOBOClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public CBOBOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public CBOBOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public bool Delete(int id)
    {
        return base.Channel.Delete(id);
    }

    public MechTech.Entities.CBODTO GetCBO(int id)
    {
        return base.Channel.GetCBO(id);
    }

    public MechTech.Entities.CBODTO GetCBOCodigo(string codigo)
    {
        return base.Channel.GetCBOCodigo(codigo);
    }

    public System.Collections.Generic.List<MechTech.Entities.CBODTO> GetGridCBO(string Campo, string ValorPesquisa)
    {
        return base.Channel.GetGridCBO(Campo, ValorPesquisa);
    }

    public int Insert(MechTech.Entities.CBODTO CBO)
    {
        return base.Channel.Insert(CBO);
    }

    public bool Update(MechTech.Entities.CBODTO CBO)
    {
        return base.Channel.Update(CBO);
    }
}
